#!/usr/bin/env python3.14
"""Generate checked-in C config schema descriptors.

This bootstrap generator intentionally understands only the tiny `fields.yaml`
subset used by the C23 tree, avoiding a Python package dependency.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_fields(path: Path) -> list[dict[str, str]]:
    fields: list[dict[str, str]] = []
    current: dict[str, str] | None = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line == "fields:":
            continue
        if line.startswith("- "):
            if current is not None:
                fields.append(current)
            current = {}
            line = line[2:]
        if ":" not in line or current is None:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
            value = value[1:-1]
        current[key.strip()] = value
    if current is not None:
        fields.append(current)
    return fields


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("fields", type=Path)
    parser.add_argument("out_c", type=Path)
    parser.add_argument("out_h", type=Path)
    args = parser.parse_args()

    type_map = {
        "string": "SC_CONFIG_FIELD_STRING",
        "int": "SC_CONFIG_FIELD_INT",
        "bool": "SC_CONFIG_FIELD_BOOL",
    }
    fields = parse_fields(args.fields)
    generated_notice = [
        "/*",
        " * Generated by tools/gen_config_schema.py.",
        " * Source input: schema/fields.yaml.",
        " * Regenerate with:",
        " *   python3.14 tools/gen_config_schema.py schema/fields.yaml src/config/sc_config_schema.c include/sc/sc_config_schema.h",
        " * Manual edits will be overwritten.",
        " */",
        "",
    ]
    header_lines = [
        *generated_notice,
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        '#include "sc/api.h"',
        '#include "sc/string.h"',
        "",
        "#define SC_CONFIG_SCHEMA_VERSION_CURRENT 2u",
        "",
        "typedef enum sc_config_field_type {",
        "    SC_CONFIG_FIELD_STRING = 0,",
        "    SC_CONFIG_FIELD_INT,",
        "    SC_CONFIG_FIELD_BOOL",
        "} sc_config_field_type;",
        "",
        "typedef struct sc_config_field {",
        "    const char *path;",
        "    sc_config_field_type type;",
        "    bool secret;",
        "    const char *default_value;",
        "    const char *doc;",
        "    uint32_t since_version;",
        "} sc_config_field;",
        "",
        "extern const sc_config_field sc_config_fields[];",
        "extern const size_t sc_config_field_count;",
        "",
        "const sc_config_field *sc_config_field_lookup(sc_str path);",
        "bool sc_config_field_is_secret(sc_str path);",
        "",
    ]

    source_lines = [
        *generated_notice,
        '#include "sc/sc_config_schema.h"',
        "",
        "#include <string.h>",
        "",
        "static bool field_path_matches(sc_str path, const char *pattern);",
        "",
        "const sc_config_field sc_config_fields[] = {",
    ]
    for field in fields:
        source_lines.extend(
            [
                "    {",
                f'        .path = "{c_escape(field["path"])}",',
                f"        .type = {type_map[field['type']]},",
                f"        .secret = {'true' if field['secret'] == 'true' else 'false'},",
                f'        .default_value = "{c_escape(field["default"])}",',
                f'        .doc = "{c_escape(field["doc"])}",',
                "        .since_version = 1,",
                "    },",
            ]
        )
    source_lines.extend(
        [
            "};",
            "",
            "const size_t sc_config_field_count = SC_ARRAY_LEN(sc_config_fields);",
            "",
            "const sc_config_field *sc_config_field_lookup(sc_str path)",
            "{",
            "    if (path.len > 0 && path.ptr == nullptr) {",
            "        return nullptr;",
            "    }",
            "",
            "    for (size_t i = 0; i < sc_config_field_count; ++i) {",
            "        if (strlen(sc_config_fields[i].path) == path.len &&",
            "            memcmp(sc_config_fields[i].path, path.ptr, path.len) == 0) {",
            "            return &sc_config_fields[i];",
            "        }",
            "    }",
            "",
            "    for (size_t i = 0; i < sc_config_field_count; ++i) {",
            "        if (field_path_matches(path, sc_config_fields[i].path)) {",
            "            return &sc_config_fields[i];",
            "        }",
            "    }",
            "",
            "    return nullptr;",
            "}",
            "",
            "static bool field_path_matches(sc_str path, const char *pattern)",
            "{",
            '    const char *wildcard = pattern == nullptr ? nullptr : strstr(pattern, "<name>");',
            "    size_t prefix_len = 0;",
            "    const char *suffix = nullptr;",
            "    size_t suffix_len = 0;",
            "    size_t name_len = 0;",
            "",
            "    if (wildcard == nullptr) {",
            "        return false;",
            "    }",
            "    prefix_len = (size_t)(wildcard - pattern);",
            '    suffix = wildcard + strlen("<name>");',
            "    suffix_len = strlen(suffix);",
            "    if (path.ptr == nullptr || path.len < prefix_len + suffix_len + 1U) {",
            "        return false;",
            "    }",
            "    if (memcmp(path.ptr, pattern, prefix_len) != 0) {",
            "        return false;",
            "    }",
            "    if (suffix_len > 0 && memcmp(path.ptr + path.len - suffix_len, suffix, suffix_len) != 0) {",
            "        return false;",
            "    }",
            "    name_len = path.len - prefix_len - suffix_len;",
            "    if (name_len == 0) {",
            "        return false;",
            "    }",
            "    for (size_t i = 0; i < name_len; ++i) {",
            "        char ch = path.ptr[prefix_len + i];",
            "        if (ch == '.') {",
            "            return false;",
            "        }",
            "    }",
            "    return true;",
            "}",
            "",
            "bool sc_config_field_is_secret(sc_str path)",
            "{",
            "    const sc_config_field *field = sc_config_field_lookup(path);",
            "    return field != nullptr && field->secret;",
            "}",
            "",
        ]
    )
    args.out_h.parent.mkdir(parents=True, exist_ok=True)
    args.out_c.parent.mkdir(parents=True, exist_ok=True)
    args.out_h.write_text("\n".join(header_lines), encoding="utf-8")
    args.out_c.write_text("\n".join(source_lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
