option(SC_BUILD_FULL "Enable common runtime features together." OFF)

option(SC_ENABLE_RUNTIME "Build agent runtime." ON)
option(SC_ENABLE_GATEWAY "Build HTTP, WebSocket, and SSE gateway." OFF)
option(SC_ENABLE_PLUGINS "Enable dynamic C ABI modules." OFF)
option(SC_ENABLE_WASM_PLUGINS "Enable WASM plugin host." OFF)
option(SC_ENABLE_PYTHON_PLUGINS "Enable in-process Python tool plugin host." OFF)
option(SC_ENABLE_HARDWARE "Enable hardware support." OFF)
option(SC_ENABLE_POSTGRES "Enable PostgreSQL memory backend." OFF)
option(SC_ENABLE_VOICE "Enable voice wake/call features." OFF)
option(SC_ENABLE_AUDIO_PREPROCESSING "Enable optional audio preprocessing libraries." OFF)
option(SC_ENABLE_CURL_HTTP2 "Build GitHub-provided libcurl with HTTP/2 support through nghttp2." OFF)
option(SC_ENABLE_MIMALLOC "Use mimalloc for the default heap allocator when available." OFF)
option(SC_ENABLE_JEMALLOC "Use jemalloc for the default heap allocator when available." OFF)

option(SC_PROVIDER_OPENAI "Build OpenAI provider." ON)
option(SC_PROVIDER_ANTHROPIC "Build Anthropic provider." ON)
option(SC_PROVIDER_GEMINI "Build Gemini provider." ON)
option(SC_PROVIDER_OLLAMA "Build Ollama provider." ON)
option(SC_PROVIDER_BEDROCK "Build Amazon Bedrock provider." ON)
option(SC_PROVIDER_OPENAI_COMPATIBLE "Build OpenAI-compatible provider adapters and presets." ON)
option(SC_PROVIDER_PROCESS_ADAPTERS "Build local process-backed provider adapter stubs." ON)

option(SC_CHANNEL_TELEGRAM "Build Telegram channel." OFF)
option(SC_CHANNEL_DISCORD "Build Discord channel." OFF)
option(SC_CHANNEL_WEBHOOK "Build webhook channel." OFF)
option(SC_CHANNEL_RABBITMQ "Build RabbitMQ channel." OFF)
option(SC_CHANNEL_MAIL "Build mail channel." OFF)

option(SC_SANITIZERS "Enable sanitizer build flags." OFF)
option(SC_FUZZING "Build coverage-guided libFuzzer targets." OFF)
option(SC_HARDENING "Enable production hardening flags." ON)

if(SC_ENABLE_WASM_PLUGINS AND NOT SC_ENABLE_PLUGINS)
    message(FATAL_ERROR "SC_ENABLE_WASM_PLUGINS=ON requires SC_ENABLE_PLUGINS=ON.")
endif()
if(SC_ENABLE_PYTHON_PLUGINS AND NOT SC_ENABLE_PLUGINS)
    message(FATAL_ERROR "SC_ENABLE_PYTHON_PLUGINS=ON requires SC_ENABLE_PLUGINS=ON.")
endif()

if(SC_BUILD_FULL)
    set(SC_ENABLE_RUNTIME ON CACHE BOOL "Build agent runtime." FORCE)
    set(SC_ENABLE_GATEWAY ON CACHE BOOL "Build HTTP, WebSocket, and SSE gateway." FORCE)
    set(SC_PROVIDER_OPENAI ON CACHE BOOL "Build OpenAI provider." FORCE)
    set(SC_PROVIDER_ANTHROPIC ON CACHE BOOL "Build Anthropic provider." FORCE)
    set(SC_PROVIDER_GEMINI ON CACHE BOOL "Build Gemini provider." FORCE)
    set(SC_PROVIDER_OLLAMA ON CACHE BOOL "Build Ollama provider." FORCE)
    set(SC_PROVIDER_BEDROCK ON CACHE BOOL "Build Amazon Bedrock provider." FORCE)
    set(SC_PROVIDER_OPENAI_COMPATIBLE ON CACHE BOOL "Build OpenAI-compatible provider adapters and presets." FORCE)
    set(SC_PROVIDER_PROCESS_ADAPTERS ON CACHE BOOL "Build local process-backed provider adapter stubs." FORCE)
    set(SC_CHANNEL_WEBHOOK ON CACHE BOOL "Build webhook channel." FORCE)
    set(SC_CHANNEL_RABBITMQ ON CACHE BOOL "Build RabbitMQ channel." FORCE)
    set(SC_CHANNEL_MAIL ON CACHE BOOL "Build mail channel." FORCE)
endif()

if(DEFINED SC_HAVE_CURL_HTTP2 AND SC_HAVE_CURL_HTTP2)
    set(SC_ENABLE_CURL_HTTP2 ON CACHE BOOL "Build GitHub-provided libcurl with HTTP/2 support through nghttp2." FORCE)
endif()

if(SC_ENABLE_MIMALLOC AND SC_ENABLE_JEMALLOC)
    message(FATAL_ERROR "Choose only one default heap backend: SC_ENABLE_MIMALLOC or SC_ENABLE_JEMALLOC.")
endif()

function(sc_bool_to_int option_name output_name)
    if(${option_name})
        set(${output_name} 1 PARENT_SCOPE)
    else()
        set(${output_name} 0 PARENT_SCOPE)
    endif()
endfunction()
