/*
 * Generated by tools/gen_config_schema.py.
 * Source input: schema/fields.yaml.
 * Regenerate with:
 *   python3.14 tools/gen_config_schema.py schema/fields.yaml src/config/sc_config_schema.c include/sc/sc_config_schema.h
 * Manual edits will be overwritten.
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

#include "sc/api.h"
#include "sc/string.h"

#define SC_CONFIG_SCHEMA_VERSION_CURRENT 2u

typedef enum sc_config_field_type {
    SC_CONFIG_FIELD_STRING = 0,
    SC_CONFIG_FIELD_INT,
    SC_CONFIG_FIELD_BOOL
} sc_config_field_type;

typedef struct sc_config_field {
    const char *path;
    sc_config_field_type type;
    bool secret;
    const char *default_value;
    const char *doc;
    uint32_t since_version;
} sc_config_field;

extern const sc_config_field sc_config_fields[];
extern const size_t sc_config_field_count;

const sc_config_field *sc_config_field_lookup(sc_str path);
bool sc_config_field_is_secret(sc_str path);
